- name: Install proftpd
  package:
    name:
      - proftpd
      - proftpd-mod-crypto
  register: proftpd_package

#- name: Remove default proftpd config
#  shell: rm -rf /etc/proftpd/*
#  when: proftpd_package is changed
#
- name: Install proftpd config files
  template:
    src: "{{ item }}"
    dest: /etc/proftpd/
    mode: 0600
    owner: proftpd
  with_items:
    - proftpd.conf
    #- modules.conf
    - tls.conf
  notify: restart proftpd

- name: Enable tls module
  lineinfile:
    path: /etc/proftpd/modules.conf
    line: LoadModule mod_tls.c
    regex: '#?LoadModule mod_tls.c'
  notify: restart proftpd

- name: Copy custom proftpd config files
  copy:
    src: "{{ proftpd_config_path }}"
    dest: "/etc/proftpd/"
    mode: 0600
    owner: proftpd
  notify: restart proftpd

